############################
## Author
############################

author:
  name: Masum Osman Khan
  image: author.png
  greeting: "Senior Software Engineer || Backend Engineer L2 @ 10 MS || DevOps"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/Masum-Osman/masum-osman.github.io
  # - link: https://github.com/Masum-Osman/masum-osman.github.io#readme
  # - website: 
  - x-twitter: https://twitter.com/masum_osman
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/masumosman/
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  - dev: https://dev.to/masumosman
  - email: osmanmasum.cs@gmail.com
  # - discord: 
  # - orcid: 
  # - slack: 
  - stack-overflow: https://stackoverflow.com/users/7086610/osman-gani-khan-masum
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  - medium: https://masum26.medium.com/
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: masum-osman.github.io
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
